# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.cache/wt [current_project]
set_property parent.project_path C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Sumator_4biti.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/myPackage.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Sumator_zecimal.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/UC_met2.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/UC_Met1.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/SRRN.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/bistabil_retine_numar.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Cascadare_sumatoare_zecimale.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/display7segments.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/UC_Principala.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Metoda2_inmultire.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Debouncer.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/bistabil_semn.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Metoda1_inmultire.vhd
  C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/sources_1/new/Modul_principal.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/constrs_1/new/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Facultate/SEM1_3/SSC_PROIECT/Implementare_1/Implementare_1.srcs/constrs_1/new/Nexys4DDR_Master.xdc]


synth_design -top Modul_principal -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Modul_principal.dcp

catch { report_utilization -file Modul_principal_utilization_synth.rpt -pb Modul_principal_utilization_synth.pb }
